# Generated by Django 5.2.7 on 2025-11-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(help_text='Nombre del instalador', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del instalador', max_length=100, verbose_name='Apellido')),
                ('documento', models.CharField(help_text='DNI, Cédula, Pasaporte, etc.', max_length=50, unique=True, verbose_name='Documento de Identidad')),
                ('email', models.EmailField(help_text='Correo electrónico del instalador', max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde opera el instalador', max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VACACIONES', 'En Vacaciones'), ('BAJA', 'De Baja')], default='ACTIVO', help_text='Estado actual del instalador', max_length=20, verbose_name='Estado')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('especialidad', models.CharField(blank=True, help_text='Ej: Cortinas motorizadas, Persianas, Instalaciones rápidas', max_length=100, verbose_name='Especialidad')),
                ('calificacion', models.DecimalField(decimal_places=2, default=0.0, help_text='Calificación promedio (0-5)', max_digits=3, verbose_name='Calificación')),
                ('total_instalaciones', models.PositiveIntegerField(default=0, help_text='Número total de instalaciones completadas', verbose_name='Total de Instalaciones')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el instalador', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Instalador',
                'verbose_name_plural': 'Instaladores',
                'ordering': ['nombre', 'apellido'],
                'indexes': [models.Index(fields=['documento'], name='instaladore_documen_f03647_idx'), models.Index(fields=['estado'], name='instaladore_estado_f19b35_idx'), models.Index(fields=['ciudad'], name='instaladore_ciudad_b9287a_idx')],
            },
        ),
    ]
