# Generated by Django 5.2.7 on 2025-12-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactura',
            name='cargo',
            field=models.CharField(choices=[('MANUFACTURADOR', 'Manufacturador'), ('INSTALADOR', 'Instalador'), ('COMERCIAL', 'Comercial')], default='INSTALADOR', help_text='Tipo de trabajo: Manufacturador o Instalador', max_length=20, verbose_name='Cargo'),
        ),
    ]
