# Generated by Django 5.2.7 on 2025-12-01 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('codigo', models.CharField(help_text='Formato sugerido: CAT-TIP-000 (Ej: COR-WAV-001)', max_length=50, unique=True, verbose_name='Código Interno')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Comercial')),
                ('tipo_producto', models.CharField(choices=[('CORTINA', 'Cortina (Textil)'), ('PERSIANA', 'Persiana (Mecánica)'), ('TOLDO', 'Toldo (Exterior)'), ('MOTOR', 'Motor / Automatización'), ('RIEL', 'Rieles y Barrales'), ('SERVICIO', 'Servicio (Mano de Obra)'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Producto')),
                ('unidad_medida', models.CharField(choices=[('M2', 'Metros Cuadrados'), ('ML', 'Metros Lineales'), ('UN', 'Unidad'), ('GL', 'Global')], default='UN', max_length=5, verbose_name='Unidad de Medida')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Base (Lista)')),
                ('requiere_medidas', models.BooleanField(default=False, help_text='Si es True, el sistema obligará a ingresar Ancho y Alto.', verbose_name='¿Requiere Medidas?')),
                ('configuracion_ui', models.JSONField(blank=True, default=dict, help_text="JSON que define qué inputs mostrar. Ej: {'pide_tejido': true, 'pide_riel': true}", verbose_name='Configuración de Interfaz (UI)')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Producto / Servicio',
                'verbose_name_plural': 'Catálogo de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddIndex(
            model_name='productoservicio',
            index=models.Index(fields=['tipo_producto'], name='productos_s_tipo_pr_d551d8_idx'),
        ),
        migrations.AddIndex(
            model_name='productoservicio',
            index=models.Index(fields=['codigo'], name='productos_s_codigo_ab3c89_idx'),
        ),
    ]
