# Generated by Django 5.2.7 on 2025-11-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_documento', models.CharField(blank=True, help_text='Número completo del documento de identificación', max_length=50, null=True, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección Completa')),
                ('telefono', models.CharField(blank=True, help_text='Incluir código de país', max_length=20, verbose_name='Teléfono/Celular')),
                ('num_contacto', models.CharField(blank=True, help_text='Número adicional para contactarse con el cliente', max_length=20, null=True, verbose_name='Número de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('tipo', models.CharField(choices=[('NUEVO', 'Nuevo'), ('RECURRENTE', 'Recurrente'), ('VIP', 'VIP')], default='NUEVO', max_length=20, verbose_name='Tipo de Cliente')),
                ('origen', models.CharField(choices=[('RECOMENDACION', 'Recomendación'), ('WEB', 'Sitio Web'), ('COLABORADOR', 'Colaborador'), ('REDES_SOCIALES', 'Redes Sociales'), ('FERIA', 'Feria o Evento'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Origen del Cliente')),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Última Compra')),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Gastado')),
                ('numero_de_compras', models.PositiveIntegerField(default=0, verbose_name='Número de Compras')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('preferencias_contacto', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada'), ('SMS', 'SMS')], default='WHATSAPP', max_length=10, verbose_name='Preferencia de Contacto')),
                ('datos_especificos', models.JSONField(blank=True, default=dict, help_text='Datos adicionales específicos del país/tipo de documento', verbose_name='Datos Específicos por País')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at', 'nombre'],
            },
        ),
    ]
