# Generated by Django 5.2.7 on 2025-11-18 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_documento', models.CharField(help_text='Número completo del documento de identificación', max_length=50, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección Completa')),
                ('telefono', models.CharField(blank=True, help_text='Incluir código de país', max_length=20, verbose_name='Teléfono/Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('tipo', models.CharField(choices=[('NUEVO', 'Nuevo'), ('RECURRENTE', 'Recurrente'), ('VIP', 'VIP')], default='NUEVO', max_length=20, verbose_name='Tipo de Cliente')),
                ('origen', models.CharField(choices=[('RECOMENDACION', 'Recomendación'), ('WEB', 'Sitio Web'), ('COLABORADOR', 'Colaborador'), ('REDES_SOCIALES', 'Redes Sociales'), ('FERIA', 'Feria o Evento'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Origen del Cliente')),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Última Compra')),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Gastado')),
                ('numero_de_compras', models.PositiveIntegerField(default=0, verbose_name='Número de Compras')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('preferencias_contacto', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada'), ('SMS', 'SMS')], default='WHATSAPP', max_length=10, verbose_name='Preferencia de Contacto')),
                ('datos_especificos', models.JSONField(blank=True, default=dict, help_text='Datos adicionales específicos del país/tipo de documento', verbose_name='Datos Específicos por País')),
                ('pais', models.ForeignKey(help_text='País de origen del cliente', on_delete=django.db.models.deletion.PROTECT, to='common.pais', verbose_name='País')),
                ('tipo_documento', models.ForeignKey(help_text='Tipo de documento de identificación', on_delete=django.db.models.deletion.PROTECT, to='common.tipodocumentoconfig', verbose_name='Tipo de Documento')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at', 'nombre'],
                'indexes': [models.Index(fields=['pais', 'tipo_documento'], name='clientes_cl_pais_id_ad6827_idx'), models.Index(fields=['numero_documento'], name='clientes_cl_numero__868cb7_idx'), models.Index(fields=['tipo', 'is_active'], name='clientes_cl_tipo_0c8b5c_idx'), models.Index(fields=['fecha_ultima_compra'], name='clientes_cl_fecha_u_ad8d7c_idx'), models.Index(fields=['total_gastado'], name='clientes_cl_total_g_ecd7d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('pais', 'tipo_documento', 'numero_documento'), name='unique_documento_por_pais_tipo')],
            },
        ),
    ]
