# Generated by Django 5.2.7 on 2025-11-20 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número completo del documento de identificación', max_length=50, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, help_text='Tipo de documento de identificación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.tipodocumentoconfig', verbose_name='Tipo de Documento'),
        ),
    ]
