# Generated by Django 5.2.7 on 2025-11-28 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(help_text='País de origen del cliente', on_delete=django.db.models.deletion.PROTECT, to='common.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, help_text='Tipo de documento de identificación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.tipodocumentoconfig', verbose_name='Tipo de Documento'),
        ),
    ]
