# Generated by Django 5.2.7 on 2025-11-28 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['pais', 'tipo_documento'], name='clientes_cl_pais_id_ad6827_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['numero_documento'], name='clientes_cl_numero__868cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tipo', 'is_active'], name='clientes_cl_tipo_0c8b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['fecha_ultima_compra'], name='clientes_cl_fecha_u_ad8d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['total_gastado'], name='clientes_cl_total_g_ecd7d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('pais', 'tipo_documento', 'numero_documento'), name='unique_documento_por_pais_tipo'),
        ),
    ]
