# Generated by Django 5.2.7 on 2025-11-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='numero_orden',
            field=models.CharField(blank=True, editable=False, help_text='Identificador único de la orden (ej: OC-0000001)', max_length=50, null=True, unique=True, verbose_name='Número de Orden'),
        ),
    ]
