# Generated by Django 5.2.7 on 2025-11-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código ISO 3166-1 Alfa-2')),
                ('codigo_telefono', models.CharField(max_length=5, verbose_name='Código de Teléfono')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TablaCorrelativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre', models.CharField(help_text='Ej: Pedidos de Servicio, Cotizaciones, Órdenes de Compra', max_length=100, unique=True, verbose_name='Nombre del Correlativo')),
                ('prefijo', models.CharField(help_text='Prefijo único para el documento (ej: PED, COT, OC, FV)', max_length=10, unique=True, verbose_name='Prefijo/Serie')),
                ('numero', models.PositiveIntegerField(default=0, help_text='Número actual del correlativo (se incrementa automáticamente)', verbose_name='Número Correlativo Actual')),
                ('longitud', models.PositiveIntegerField(default=7, help_text='Cantidad de dígitos a rellenar con ceros (ej: 7 para 0000001)', verbose_name='Longitud del Número')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=12, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional sobre este correlativo', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tabla de Correlativos',
                'verbose_name_plural': 'Tablas de Correlativos',
                'db_table': 'common_tabla_correlativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Documento')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código del Documento')),
                ('regex_validacion', models.CharField(blank=True, max_length=255, verbose_name='Regex de Validación')),
                ('mensaje_error', models.CharField(blank=True, max_length=255, verbose_name='Mensaje de Error de Validación')),
                ('es_para_empresa', models.BooleanField(default=False, verbose_name='¿Es para Empresa?')),
                ('longitud_minima', models.PositiveIntegerField(default=1, verbose_name='Longitud Mínima')),
                ('longitud_maxima', models.PositiveIntegerField(default=50, verbose_name='Longitud Máxima')),
            ],
            options={
                'verbose_name': 'Configuración de Tipo de Documento',
                'verbose_name_plural': 'Configuraciones de Tipos de Documento',
                'ordering': ['pais__nombre', 'nombre'],
            },
        ),
    ]
