# Generated by Django 5.2.7 on 2025-11-18 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código ISO 3166-1 Alfa-2')),
                ('codigo_telefono', models.CharField(max_length=5, verbose_name='Código de Teléfono')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Documento')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código del Documento')),
                ('regex_validacion', models.CharField(blank=True, max_length=255, verbose_name='Regex de Validación')),
                ('mensaje_error', models.CharField(blank=True, max_length=255, verbose_name='Mensaje de Error de Validación')),
                ('es_para_empresa', models.BooleanField(default=False, verbose_name='¿Es para Empresa?')),
                ('longitud_minima', models.PositiveIntegerField(default=1, verbose_name='Longitud Mínima')),
                ('longitud_maxima', models.PositiveIntegerField(default=50, verbose_name='Longitud Máxima')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='common.pais')),
            ],
            options={
                'verbose_name': 'Configuración de Tipo de Documento',
                'verbose_name_plural': 'Configuraciones de Tipos de Documento',
                'ordering': ['pais__nombre', 'nombre'],
                'unique_together': {('pais', 'codigo')},
            },
        ),
    ]
