# Generated by Django 5.2.7 on 2025-11-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaCorrelativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre', models.CharField(help_text='Ej: Pedidos de Servicio, Cotizaciones, Órdenes de Compra', max_length=100, unique=True, verbose_name='Nombre del Correlativo')),
                ('prefijo', models.CharField(help_text='Prefijo único para el documento (ej: PED, COT, OC, FV)', max_length=10, unique=True, verbose_name='Prefijo/Serie')),
                ('numero', models.PositiveIntegerField(default=0, help_text='Número actual del correlativo (se incrementa automáticamente)', verbose_name='Número Correlativo Actual')),
                ('longitud', models.PositiveIntegerField(default=7, help_text='Cantidad de dígitos a rellenar con ceros (ej: 7 para 0000001)', verbose_name='Longitud del Número')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=12, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional sobre este correlativo', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tabla de Correlativos',
                'verbose_name_plural': 'Tablas de Correlativos',
                'db_table': 'common_tabla_correlativos',
                'ordering': ['nombre'],
            },
        ),
    ]
