# Generated by Django 5.2.7 on 2025-12-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_initial'),
        ('manufactura', '0002_alter_manufactura_cargo'),
        ('productos_servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('numero', models.CharField(editable=False, help_text='Generado automáticamente (Ej: COT-000015)', max_length=50, unique=True, verbose_name='Número de Cotización')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_validez', models.DateField(blank=True, null=True, verbose_name='Válida hasta')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al Cliente'), ('ACEPTADA', 'Aceptada (Cerrada)'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20, verbose_name='Estado Actual')),
                ('total_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Subtotal Neto')),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Descuento Total')),
                ('total_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total General')),
                ('observaciones', models.TextField(blank=True, help_text='Notas visibles en el PDF para el cliente', verbose_name='Observaciones Comerciales')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('vendedor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'VENDEDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_realizadas', to='manufactura.manufactura', verbose_name='Vendedor Responsable')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
                'permissions': [('can_change_status_accepted', 'Puede aprobar cotización (Aceptada)'), ('can_reactivate_cotizacion', 'Puede reactivar cotización vencida'), ('can_convert_to_pedido', 'Puede convertir cotización a pedido'), ('can_apply_extra_discount', 'Puede aplicar descuento extra'), ('can_override_unit_price', 'Puede sobrescribir precio unitario')],
            },
        ),
        migrations.CreateModel(
            name='CotizacionAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Ambiente')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar en el PDF')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='cotizaciones.cotizacion')),
            ],
            options={
                'verbose_name': 'Ambiente de Cotización',
                'verbose_name_plural': 'Ambientes de Cotización',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_item', models.PositiveIntegerField(verbose_name='#')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Ancho (m)')),
                ('alto', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Alto (m)')),
                ('atributos_seleccionados', models.JSONField(blank=True, default=dict, help_text="Ej: {'tejido': 'Linho', 'riel': 'Blanco', 'comando': 'Izq'}", verbose_name='Atributos Seleccionados (JSON)')),
                ('descripcion_tecnica', models.TextField(blank=True, editable=False, help_text='Texto final generado para el PDF.', verbose_name='Descripción Generada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario Base (Snapshot)')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento Línea (%)')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Línea (Neto)')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacionambiente', verbose_name='Ambiente Padre')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_cotizados', to='productos_servicios.productoservicio', verbose_name='Producto del Catálogo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Ítem de Cotización',
                'verbose_name_plural': 'Ítems de Cotización',
                'ordering': ['numero_item'],
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado', '-created_at'], name='cotizacione_estado_842622_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente'], name='cotizacione_cliente_b0cc9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotizacionitem',
            unique_together={('ambiente', 'numero_item')},
        ),
    ]
