# Generated by Django 5.2.7 on 2025-12-05 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('manufactura', '0002_alter_manufactura_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'COMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_realizadas', to='manufactura.manufactura', verbose_name='Vendedor Responsable'),
        ),
    ]
