# Generated by Django 5.2.7 on 2025-12-06 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_remove_cotizacion_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de emisión de la cotización (se establece automáticamente)', verbose_name='Fecha de Emisión'),
        ),
    ]
