# Generated by Django 5.2.7 on 2025-12-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_cotizacion_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, help_text='Fecha de emisión de la cotización (se establece automáticamente)', verbose_name='Fecha de Emisión'),
        ),
    ]
