# Generated by Django 5.2.7 on 2025-11-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(help_text='Nombre del producto o servicio', max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto o servicio', null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta al público o costo estándar', max_digits=10)),
                ('es_servicio', models.BooleanField(default=False, help_text='Marcar si es un servicio en lugar de un producto físico')),
            ],
            options={
                'verbose_name': 'Producto o Servicio',
                'verbose_name_plural': 'Productos y Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
