
# Generated by Django 5.2.7 on 2025-11-20 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('instaladores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_pedido', models.CharField(help_text='Identificador único del pedido', max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('solicitante', models.CharField(help_text='Nombre de quien solicita el servicio', max_length=200, verbose_name='Solicitante')),
                ('supervisor', models.CharField(blank=True, help_text='Supervisor asignado', max_length=200, verbose_name='Supervisor')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('EN_FABRICACION', 'En Fabricación'), ('LISTO_INSTALAR', 'Listo para Instalar'), ('INSTALADO', 'Instalado'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='ENVIADO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_servicio', to='clientes.cliente', verbose_name='Cliente')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_servicio', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Pedido de Servicio',
                'verbose_name_plural': 'Pedidos de Servicio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', '-created_at'], name='pedidos_ser_estado_0001_idx'), models.Index(fields=['cliente', 'estado'], name='pedidos_ser_cliente_0002_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('numero_item', models.IntegerField(verbose_name='Número de Item')),
                ('ambiente', models.CharField(max_length=200, verbose_name='Ambiente')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('tejido', models.CharField(max_length=200, verbose_name='Tejido')),
                ('largura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largura (m)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura (m)')),
                ('cantidad_piezas', models.IntegerField(verbose_name='Cantidad de Piezas')),
                ('posicion_tejido', models.CharField(choices=[('NORMAL', 'Normal'), ('INVERSO', 'Inverso')], default='NORMAL', max_length=20, verbose_name='Posición del Tejido')),
                ('lado_comando', models.CharField(choices=[('IZQUIERDO', 'Izquierdo'), ('DERECHO', 'Derecho'), ('AMBOS', 'Ambos')], default='IZQUIERDO', max_length=20, verbose_name='Lado del Comando')),
                ('acionamiento', models.CharField(choices=[('MANUAL', 'Manual'), ('MOTORIZADO', 'Motorizado')], default='MANUAL', max_length=20, verbose_name='Accionamiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos_servicio.pedidoservicio', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedidos',
                'ordering': ['numero_item'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_tarea', models.CharField(choices=[('FABRICACION', 'Fabricación'), ('INSTALACION', 'Instalación')], help_text='¿Es fabricación o instalación?', max_length=20, verbose_name='Tipo de Tarea')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Tarea')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio Real')),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Esperada')),
                ('fecha_completacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completación')),
                ('descripcion_tarea', models.TextField(blank=True, help_text='Detalles específicos de lo que debe hacerse', verbose_name='Descripción de la Tarea')),
                ('notas_progreso', models.TextField(blank=True, help_text='Actualizaciones durante la ejecución', verbose_name='Notas de Progreso')),
                ('instalador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='instaladores.instalador', verbose_name='Instalador/Fabricante')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='pedidos_servicio.pedidoservicio', verbose_name='Pedido de Servicio')),
            ],
            options={
                'verbose_name': 'Asignación de Tarea',
                'verbose_name_plural': 'Asignaciones de Tareas',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['instalador', 'estado'], name='pedidos_ser_instala_b8526b_idx'), models.Index(fields=['pedido', 'tipo_tarea'], name='pedidos_ser_pedido__f07a19_idx'), models.Index(fields=['estado', '-fecha_asignacion'], name='pedidos_ser_estado_c48352_idx')],
                'constraints': [models.UniqueConstraint(fields=('pedido', 'tipo_tarea', 'instalador'), name='unique_asignacion_por_tipo')],
            },
        ),
    ]
