# Generated by Django 5.2.7 on 2025-11-21 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_numero_documento_and_more'),
        ('instaladores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_pedido', models.CharField(max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('descripcion', models.TextField(verbose_name='Descripción del Servicio')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('FABRICACION', 'Fabricación'), ('INSTALACION', 'Instalación'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización Esperada')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_servicio', to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_servicio_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Pedido de Servicio',
                'verbose_name_plural': 'Pedidos de Servicio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_tarea', models.CharField(choices=[('FABRICACION', 'Fabricación'), ('INSTALACION', 'Instalación'), ('MANTENIMIENTO', 'Mantenimiento'), ('REPARACION', 'Reparación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Tarea')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('descripcion_tarea', models.TextField(verbose_name='Descripción de la Tarea')),
                ('fecha_entrega_esperada', models.DateField(verbose_name='Fecha de Entrega Esperada')),
                ('fecha_completado', models.DateField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('instalador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_tareas', to='instaladores.instalador', verbose_name='Instalador Asignado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='pedidos_servicio.pedidoservicio', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Asignación de Tarea',
                'verbose_name_plural': 'Asignaciones de Tareas',
                'ordering': ['-created_at'],
            },
        ),
    ]
