# Generated by Django 5.2.7 on 2025-11-20 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_pedido', models.CharField(help_text='Identificador único del pedido', max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('direccion_instalacion', models.CharField(help_text='Dirección completa donde se realizará la instalación', max_length=500, verbose_name='Dirección de Instalación')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('medidas', models.TextField(help_text='Especificaciones técnicas de medidas (ancho, alto, etc.)', verbose_name='Medidas')),
                ('color', models.CharField(blank=True, help_text='Color o acabado requerido', max_length=100, verbose_name='Color/Acabado')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre el servicio a prestar', verbose_name='Descripción del Servicio')),
                ('fecha_programada', models.DateField(help_text='Fecha programada para la instalación', verbose_name='Fecha de Instalación')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio prevista', null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de fin prevista', null=True, verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EJECUTADO', 'Ejecutado'), ('CANCELADO', 'Cancelado')], default='ENVIADO', max_length=20, verbose_name='Estado del Pedido')),
                ('observaciones', models.TextField(blank=True, help_text='Notas internas sobre el pedido', verbose_name='Observaciones')),
                ('observaciones_cliente', models.TextField(blank=True, help_text='Preferencias o especiales requerimientos del cliente', verbose_name='Observaciones del Cliente')),
                ('telefono_contacto', models.CharField(blank=True, help_text='Teléfono del cliente para el día de la instalación', max_length=20, verbose_name='Teléfono de Contacto')),
                ('cliente', models.ForeignKey(help_text='Cliente para el cual se realiza el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_servicio', to='clientes.cliente', verbose_name='Cliente')),
                ('colaborador', models.ForeignKey(help_text='Usuario colaborador que genera el pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_servicio_creados', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Pedido de Servicio',
                'verbose_name_plural': 'Pedidos de Servicio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', '-created_at'], name='pedidos_ser_estado_659825_idx'), models.Index(fields=['colaborador', 'estado'], name='pedidos_ser_colabor_040fc6_idx'), models.Index(fields=['cliente', 'estado'], name='pedidos_ser_cliente_8ffec3_idx')],
            },
        ),
    ]
