# Generated by Django 5.2.7 on 2025-11-21 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_numero_documento_and_more'),
        ('instaladores', '0001_initial'),
        ('pedidos_servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('ambiente', models.CharField(help_text='Nombre del ambiente (ej: Varanda, Sala, Dormitorio)', max_length=200, verbose_name='Ambiente')),
                ('modelo', models.CharField(help_text='Modelo de cortina (ej: Rolô, Persiana, Panel)', max_length=100, verbose_name='Modelo')),
                ('tejido', models.CharField(help_text='Tipo y características del tejido (ej: Screen 3% branco)', max_length=150, verbose_name='Tejido')),
                ('largura', models.DecimalField(decimal_places=2, help_text='Ancho/Largura en metros', max_digits=5, verbose_name='Largura (m)')),
                ('altura', models.DecimalField(decimal_places=2, help_text='Alto/Altura en metros', max_digits=5, verbose_name='Altura (m)')),
                ('cantidad_piezas', models.PositiveIntegerField(help_text='Número de unidades iguales', verbose_name='Cantidad de Piezas')),
                ('posicion_tejido', models.CharField(choices=[('NORMAL', 'Normal'), ('INVERSO', 'Inverso')], default='NORMAL', max_length=20, verbose_name='Posición del Tejido')),
                ('lado_comando', models.CharField(choices=[('IZQUIERDO', 'Izquierdo'), ('DERECHO', 'Derecho'), ('AMBOS', 'Ambos')], help_text='Lado donde va instalado el comando/control', max_length=20, verbose_name='Lado del Comando')),
                ('acionamiento', models.CharField(choices=[('MANUAL', 'Manual'), ('MOTORIZADO', 'Motorizado')], max_length=20, verbose_name='Accionamiento')),
                ('observaciones', models.TextField(blank=True, help_text='Notas específicas para este item (ej: instalación por fuera del vão)', verbose_name='Observaciones')),
                ('numero_item', models.PositiveIntegerField(help_text='Orden del item dentro del pedido', verbose_name='Número de Item')),
            ],
            options={
                'verbose_name': 'Item de Pedido de Servicio',
                'verbose_name_plural': 'Items de Pedidos de Servicio',
                'ordering': ['numero_item'],
            },
        ),
        migrations.AlterModelOptions(
            name='asignaciontarea',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'Asignación de Tarea', 'verbose_name_plural': 'Asignaciones de Tareas'},
        ),
        migrations.RemoveField(
            model_name='asignaciontarea',
            name='fecha_completado',
        ),
        migrations.RemoveField(
            model_name='asignaciontarea',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Asignación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='fecha_completacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completación'),
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='fecha_inicio_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio Real'),
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='notas_progreso',
            field=models.TextField(blank=True, help_text='Actualizaciones durante la ejecución', verbose_name='Notas de Progreso'),
        ),
        migrations.AddField(
            model_name='pedidoservicio',
            name='colaborador',
            field=models.ForeignKey(blank=True, help_text='Instalador asignado para realizar la instalación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_servicio', to='instaladores.instalador', verbose_name='Instalador'),
        ),
        migrations.AddField(
            model_name='pedidoservicio',
            name='solicitante',
            field=models.CharField(blank=True, help_text='Persona que solicita el pedido (ej: Sra. Rita)', max_length=150, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='pedidoservicio',
            name='supervisor',
            field=models.CharField(blank=True, help_text='Persona que supervisa la instalación', max_length=150, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='descripcion_tarea',
            field=models.TextField(blank=True, help_text='Detalles específicos de lo que debe hacerse', verbose_name='Descripción de la Tarea'),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Tarea'),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='fecha_entrega_esperada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Esperada'),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='instalador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='instaladores.instalador', verbose_name='Instalador/Fabricante'),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='pedidos_servicio.pedidoservicio', verbose_name='Pedido de Servicio'),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='tipo_tarea',
            field=models.CharField(choices=[('FABRICACION', 'Fabricación'), ('INSTALACION', 'Instalación')], help_text='¿Es fabricación o instalación?', max_length=20, verbose_name='Tipo de Tarea'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente para el cual se realiza el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_servicio', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('EN_FABRICACION', 'En Fabricación'), ('LISTO_INSTALAR', 'Listo para Instalar'), ('INSTALADO', 'Instalado'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='ENVIADO', max_length=20, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha prevista de finalización de instalación', null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha prevista de inicio de instalación', null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='numero_pedido',
            field=models.CharField(editable=False, help_text='Identificador único del pedido (ej: PED-0000001)', max_length=50, unique=True, verbose_name='Número de Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas internas sobre el pedido completo', verbose_name='Observaciones Generales'),
        ),
        migrations.AddIndex(
            model_name='asignaciontarea',
            index=models.Index(fields=['instalador', 'estado'], name='pedidos_ser_instala_b8526b_idx'),
        ),
        migrations.AddIndex(
            model_name='asignaciontarea',
            index=models.Index(fields=['pedido', 'tipo_tarea'], name='pedidos_ser_pedido__f07a19_idx'),
        ),
        migrations.AddIndex(
            model_name='asignaciontarea',
            index=models.Index(fields=['estado', '-fecha_asignacion'], name='pedidos_ser_estado_c48352_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoservicio',
            index=models.Index(fields=['estado', '-created_at'], name='pedidos_ser_estado_659825_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoservicio',
            index=models.Index(fields=['cliente', 'estado'], name='pedidos_ser_cliente_8ffec3_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoservicio',
            index=models.Index(fields=['colaborador', 'estado'], name='pedidos_ser_colabor_040fc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignaciontarea',
            constraint=models.UniqueConstraint(fields=('pedido', 'tipo_tarea', 'instalador'), name='unique_asignacion_por_tipo'),
        ),
        migrations.AddField(
            model_name='itempedidoservicio',
            name='pedido_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos_servicio.pedidoservicio', verbose_name='Pedido de Servicio'),
        ),
        migrations.AddIndex(
            model_name='itempedidoservicio',
            index=models.Index(fields=['pedido_servicio', 'numero_item'], name='pedidos_ser_pedido__461b72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedidoservicio',
            unique_together={('pedido_servicio', 'numero_item')},
        ),
    ]
