# Generated by Django 5.2.7 on 2025-11-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoservicio',
            name='numero_pedido',
            field=models.CharField(editable=False, help_text='Identificador único del pedido (ej: PED-0000001)', max_length=50, unique=True, verbose_name='Número de Pedido'),
        ),
    ]
