# Generated by Django 5.2.7 on 2025-11-21 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_numero_documento_and_more'),
        ('instaladores', '0001_initial'),
        ('pedidos_servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidoservicio',
            name='pedido_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos_servicio.pedidoservicio', verbose_name='Pedido de Servicio'),
        ),
        migrations.AddField(
            model_name='itempedidoservicio',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.RemoveField(
            model_name='itempedidoservicio',
            name='pedido',
        ),
        migrations.AlterModelOptions(
            name='itempedidoservicio',
            options={'ordering': ['numero_item'], 'verbose_name': 'Item de Pedido de Servicio', 'verbose_name_plural': 'Items de Pedidos de Servicio'},
        ),
        migrations.AlterUniqueTogether(
            name='itempedidoservicio',
            unique_together={('pedido_servicio', 'numero_item')},
        ),
        migrations.RenameIndex(
            model_name='pedidoservicio',
            new_name='pedidos_ser_estado_659825_idx',
            old_name='pedidos_ser_estado_0001_idx',
        ),
        migrations.RenameIndex(
            model_name='pedidoservicio',
            new_name='pedidos_ser_cliente_8ffec3_idx',
            old_name='pedidos_ser_cliente_0002_idx',
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='acionamiento',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('MOTORIZADO', 'Motorizado')], max_length=20, verbose_name='Accionamiento'),
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='altura',
            field=models.DecimalField(decimal_places=2, help_text='Alto/Altura en metros', max_digits=5, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='ambiente',
            field=models.CharField(help_text='Nombre del ambiente (ej: Varanda, Sala, Dormitorio)', max_length=200, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='cantidad_piezas',
            field=models.PositiveIntegerField(help_text='Número de unidades iguales', verbose_name='Cantidad de Piezas'),
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='lado_comando',
            field=models.CharField(choices=[('IZQUIERDO', 'Izquierdo'), ('DERECHO', 'Derecho'), ('AMBOS', 'Ambos')], help_text='Lado donde va instalado el comando/control', max_length=20, verbose_name='Lado del Comando'),
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='largura',
            field=models.DecimalField(decimal_places=2, help_text='Ancho/Largura en metros', max_digits=5, verbose_name='Largura (m)'),
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='modelo',
            field=models.CharField(help_text='Modelo de cortina (ej: Rolô, Persiana, Panel)', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='numero_item',
            field=models.PositiveIntegerField(help_text='Orden del item dentro del pedido', verbose_name='Número de Item'),
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas específicas para este item (ej: instalación por fuera del vão)', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='itempedidoservicio',
            name='tejido',
            field=models.CharField(help_text='Tipo y características del tejido (ej: Screen 3% branco)', max_length=150, verbose_name='Tejido'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente para el cual se realiza el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_servicio', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='colaborador',
            field=models.ForeignKey(blank=True, help_text='Instalador asignado para realizar la instalación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_servicio', to='instaladores.instalador', verbose_name='Instalador'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('EN_FABRICACION', 'En Fabricación'), ('LISTO_INSTALAR', 'Listo para Instalar'), ('INSTALADO', 'Instalado'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='ENVIADO', max_length=20, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha prevista de finalización de instalación', null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha prevista de inicio de instalación', null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='numero_pedido',
            field=models.CharField(editable=False, help_text='Identificador único del pedido (ej: PED-0000001)', max_length=50, unique=True, verbose_name='Número de Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas internas sobre el pedido completo', verbose_name='Observaciones Generales'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='solicitante',
            field=models.CharField(blank=True, help_text='Persona que solicita el pedido (ej: Sra. Rita)', max_length=150, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='supervisor',
            field=models.CharField(blank=True, help_text='Persona que supervisa la instalación', max_length=150, verbose_name='Supervisor'),
        ),
        migrations.AddIndex(
            model_name='itempedidoservicio',
            index=models.Index(fields=['pedido_servicio', 'numero_item'], name='pedidos_ser_pedido__461b72_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoservicio',
            index=models.Index(fields=['colaborador', 'estado'], name='pedidos_ser_colabor_040fc6_idx'),
        ),
    ]
