# Generated by Django 5.2.7 on 2025-11-20 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_servicio', '0002_alter_pedidoservicio_numero_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='direccion_instalacion',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='fecha_programada',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='medidas',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='observaciones_cliente',
        ),
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='telefono_contacto',
        ),
        migrations.AddField(
            model_name='pedidoservicio',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha prevista de finalización de instalación', null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='pedidoservicio',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha prevista de inicio de instalación', null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='pedidoservicio',
            name='solicitante',
            field=models.CharField(blank=True, help_text='Persona que solicita el pedido (ej: Sra. Rita)', max_length=150, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='pedidoservicio',
            name='supervisor',
            field=models.CharField(blank=True, help_text='Persona que supervisa la instalación', max_length=150, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='colaborador',
            field=models.ForeignKey(blank=True, help_text='Usuario colaborador que realiza la instalación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_servicio_como_instalador', to=settings.AUTH_USER_MODEL, verbose_name='Instalador'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('EN_FABRICACION', 'En Fabricación'), ('LISTO_INSTALAR', 'Listo para Instalar'), ('INSTALADO', 'Instalado'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='ENVIADO', max_length=20, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoservicio',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas internas sobre el pedido completo', verbose_name='Observaciones Generales'),
        ),
        migrations.CreateModel(
            name='ItemPedidoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('ambiente', models.CharField(help_text='Nombre del ambiente (ej: Varanda, Sala, Dormitorio)', max_length=200, verbose_name='Ambiente')),
                ('modelo', models.CharField(help_text='Modelo de cortina (ej: Rolô, Persiana, Panel)', max_length=100, verbose_name='Modelo')),
                ('tejido', models.CharField(help_text='Tipo y características del tejido (ej: Screen 3% branco)', max_length=150, verbose_name='Tejido')),
                ('largura', models.DecimalField(decimal_places=2, help_text='Ancho/Largura en metros', max_digits=5, verbose_name='Largura (m)')),
                ('altura', models.DecimalField(decimal_places=2, help_text='Alto/Altura en metros', max_digits=5, verbose_name='Altura (m)')),
                ('cantidad_piezas', models.PositiveIntegerField(help_text='Número de unidades iguales', verbose_name='Cantidad de Piezas')),
                ('posicion_tejido', models.CharField(choices=[('NORMAL', 'Normal'), ('INVERSO', 'Inverso')], default='NORMAL', max_length=20, verbose_name='Posición del Tejido')),
                ('lado_comando', models.CharField(choices=[('IZQUIERDO', 'Izquierdo'), ('DERECHO', 'Derecho'), ('AMBOS', 'Ambos')], help_text='Lado donde va instalado el comando/control', max_length=20, verbose_name='Lado del Comando')),
                ('acionamiento', models.CharField(choices=[('MANUAL', 'Manual'), ('MOTORIZADO', 'Motorizado')], max_length=20, verbose_name='Accionamiento')),
                ('observaciones', models.TextField(blank=True, help_text='Notas específicas para este item (ej: instalación por fuera del vão)', verbose_name='Observaciones')),
                ('numero_item', models.PositiveIntegerField(help_text='Orden del item dentro del pedido', verbose_name='Número de Item')),
                ('pedido_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos_servicio.pedidoservicio', verbose_name='Pedido de Servicio')),
            ],
            options={
                'verbose_name': 'Item de Pedido de Servicio',
                'verbose_name_plural': 'Items de Pedidos de Servicio',
                'ordering': ['numero_item'],
                'indexes': [models.Index(fields=['pedido_servicio', 'numero_item'], name='pedidos_ser_pedido__461b72_idx')],
                'unique_together': {('pedido_servicio', 'numero_item')},
            },
        ),
    ]
