# Generated by Django 5.2.7 on 2025-11-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_servicio', '0002_alter_pedidoservicio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoservicio',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_to_aceptado', 'Puede cambiar estado a Aceptado'), ('can_change_to_en_fabricacion', 'Puede cambiar estado a En Fabricación'), ('can_change_to_listo_instalar', 'Puede cambiar estado a Listo para Instalar'), ('can_change_to_instalado', 'Puede cambiar estado a Instalado'), ('can_change_to_completado', 'Puede cambiar estado a Completado'), ('can_change_to_rechazado', 'Puede rechazar pedidos'), ('can_change_to_cancelado', 'Puede cancelar pedidos'), ('can_delete_pedido', 'Puede eliminar pedidos en estado ENVIADO')], 'verbose_name': 'Pedido de Servicio', 'verbose_name_plural': 'Pedidos de Servicio'},
        ),
    ]
