# Generated by Django 5.2.7 on 2025-12-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_servicio', '0003_alter_pedidoservicio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoservicio',
            name='fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha en que se emitió el pedido de servicio', null=True, verbose_name='Fecha de Emisión'),
        ),
    ]
