# Generated by Django 5.2.7 on 2025-11-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaladores', '0001_initial'),
        ('pedidos_servicio', '0003_remove_pedidoservicio_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoservicio',
            name='colaborador',
            field=models.ForeignKey(blank=True, help_text='Instalador asignado para realizar la instalación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_servicio', to='instaladores.instalador', verbose_name='Instalador'),
        ),
    ]
