# Generated by Django 5.2.7 on 2025-11-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaladores', '0001_initial'),
        ('pedidos_servicio', '0004_alter_pedidoservicio_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_tarea', models.CharField(choices=[('FABRICACION', 'Fabricación'), ('INSTALACION', 'Instalación')], help_text='¿Es fabricación o instalación?', max_length=20, verbose_name='Tipo de Tarea')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Tarea')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio Real')),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Esperada')),
                ('fecha_completacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completación')),
                ('descripcion_tarea', models.TextField(blank=True, help_text='Detalles específicos de lo que debe hacerse', verbose_name='Descripción de la Tarea')),
                ('notas_progreso', models.TextField(blank=True, help_text='Actualizaciones durante la ejecución', verbose_name='Notas de Progreso')),
                ('instalador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='instaladores.instalador', verbose_name='Instalador/Fabricante')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='pedidos_servicio.pedidoservicio', verbose_name='Pedido de Servicio')),
            ],
            options={
                'verbose_name': 'Asignación de Tarea',
                'verbose_name_plural': 'Asignaciones de Tareas',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['instalador', 'estado'], name='pedidos_ser_instala_b8526b_idx'), models.Index(fields=['pedido', 'tipo_tarea'], name='pedidos_ser_pedido__f07a19_idx'), models.Index(fields=['estado', '-fecha_asignacion'], name='pedidos_ser_estado_c48352_idx')],
                'constraints': [models.UniqueConstraint(fields=('pedido', 'tipo_tarea', 'instalador'), name='unique_asignacion_por_tipo')],
            },
        ),
    ]
